### ISSUE TITLE
Nightly version - commit id

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/www.julialang.org#1660] opened 2022-04-08 07:08 UTC
Hi,
It would be nice on the nightly download page to show for which commit the binaries have been generated. I always have to download them to find out the commit id.
Thabk you

**Comment by DilumAluthge** [comment] 2022-04-08 07:12
Duplicate of https://github.com/JuliaCI/julia-buildkite/issues/35

**Closed by DilumAluthge** 2022-04-08 07:12 UTC
