### ISSUE TITLE
PR Previews are failing?

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#1059] opened 2020-10-26 08:36 UTC
cc: @logankilpatrick @DilumAluthge 

Logan pinged me with this: https://github.com/JuliaLang/www.julialang.org/runs/1306261381 

it seems the docker build is failing:

```
 Step 3/4 : RUN npm install --production
35   ---> Running in a78fb6584b9a
36  npm notice 
37  npm notice New patch version of npm available! 7.0.3 -> 7.0.5
38  npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.5>
39  npm notice Run `npm install -g npm@7.0.5` to update!
40  npm notice 
41  npm ERR! Maximum call stack size exceeded
42  
43  npm ERR! A complete log of this run can be found in:
44  npm ERR!     /root/.npm/_logs/2020-10-26T00_00_05_394Z-debug.log
45  The command '/bin/sh -c npm install --production' returned a non-zero code: 1
```

No idea what's going on there? I tried re-launching the job to check it's not just a glitch

**Comment by DilumAluthge** [comment] 2020-10-26 12:34
This should have been fixed with https://github.com/JuliaLang/www.julialang.org/pull/1058

Can you try making a new PR to see if you can reproduce?

**Comment by logankilpatrick** [comment] 2020-10-26 12:51
It seems to be working now! 

Best, 
Logan Kilpatrick

**Closed** 2020-10-26 13:15 UTC
